system:
  type: DoubleIntegrator
  feedback: FullState
  controller: constraint_default_more_data_5hz
  dagger: false

analysis:
  reachability_direction: forward
  mode: symbolic

visualization:
  save_plot: true
  show_plot: true
  show: true
  make_animation: false
  show_animation: false
  show_samples: true
  show_trajectories: false
  plot_dims: [0, 1]
  plot_axis_labels: ["$x_0$", "$x_1$"]
  plot_aspect: auto
  plot_lims: null
