system:
  type: DoubleIntegrator
  feedback: FullState
  controller: robust-constraint_expanded_5hz
  dagger: false

analysis:
  reachability_direction: forward
  partitioner:
    type: Uniform
    num_partitions: (4,4)
  propagator:
    type: CROWN
    boundary_type: rectangle
  initial_state_range: "[[2.5, 3.0], [-0.25, 0.25]]"
  t_max: 5
  estimate_runtime: false
  estimate_error: false

visualization:
  save_plot: true
  show_plot: false
  show: true
  make_animation: false
  show_animation: false
  show_samples: true
  show_trajectories: false
  plot_dims: [0, 1]
  plot_axis_labels: ["$x_0$", "$x_1$"]
  plot_aspect: auto
  plot_lims: null
